UPDATE trinity_string SET content_default='您应该选择角色或生物.' WHERE entry=1;
UPDATE trinity_string SET content_default='您应该选择一个生物.' WHERE entry=2;
UPDATE trinity_string SET content_default='|cffff0000[系统消息]: %s|r' WHERE entry=3;
UPDATE trinity_string SET content_default='|cffff0000[游戏广播]: %s|r' WHERE entry=4;
UPDATE trinity_string SET content_default='这里没有此命令的帮助信息' WHERE entry=5;
UPDATE trinity_string SET content_default='这个命令不存在' WHERE entry=6;
UPDATE trinity_string SET content_default='这里没有此类子命令' WHERE entry=7;
UPDATE trinity_string SET content_default='命令 %s 子命令是:%s' WHERE entry=8;
UPDATE trinity_string SET content_default='你可以使用的命令有:' WHERE entry=9;
UPDATE trinity_string SET content_default='命令语法格式错误.' WHERE entry=10;
UPDATE trinity_string SET content_default='你的账号级别是: %i' WHERE entry=11;
UPDATE trinity_string SET content_default='在线人数: %u (最多时: %u) 排队人数: %u (最多时: %u)' WHERE entry=12;
UPDATE trinity_string SET content_default='服务器正常运行时间: %s' WHERE entry=13;
UPDATE trinity_string SET content_default='系统提示：玩家数据保存成功.' WHERE entry=14;
UPDATE trinity_string SET content_default='系统提示：保存所有玩家数据成功.' WHERE entry=15;
UPDATE trinity_string SET content_default='系统提示：在此服务器上有以下在线的G M:' WHERE entry=16;
UPDATE trinity_string SET content_default='系统提示：当前没有G M登录在这台服务器上.' WHERE entry=17;
UPDATE trinity_string SET content_default='系统提示：当处于飞行中时，无法这样做.' WHERE entry=18;
UPDATE trinity_string SET content_default='系统提示：目标在飞行中，你无法这样做.' WHERE entry=20;
UPDATE trinity_string SET content_default='系统提示：在战场里无法这样做.' WHERE entry=19;
UPDATE trinity_string SET content_default='%s 正在飞行中, 命令无效.' WHERE entry=21;
UPDATE trinity_string SET content_default='系统提示：你没有在骑乘状态, 因此你不能卸下骑乘.' WHERE entry=22;
UPDATE trinity_string SET content_default='系统提示：在战斗中无法这样做.' WHERE entry=23;
UPDATE trinity_string SET content_default='系统提示：您最近已经使用过它.' WHERE entry=24;
UPDATE trinity_string SET content_default='系统提示：您的密码不能设置超过16个字符长度(客户极限), 密码没被改变' WHERE entry=25;
UPDATE trinity_string SET content_default='系统提示：密码已经修改.' WHERE entry=26;
UPDATE trinity_string SET content_default='系统提示：新新口令不匹配或旧密码是错误的.' WHERE entry=27;
UPDATE trinity_string SET content_default='系统提示：你的账号现在被锁定.' WHERE entry=28;
UPDATE trinity_string SET content_default='系统提示：你的账号已取消锁定.' WHERE entry=29;
UPDATE trinity_string SET content_default='排名 ' WHERE entry=30;
UPDATE trinity_string SET content_default=' [学会]' WHERE entry=31;
UPDATE trinity_string SET content_default=' [学习]' WHERE entry=32;
UPDATE trinity_string SET content_default=' [被动的]' WHERE entry=33;
UPDATE trinity_string SET content_default=' [天赋]' WHERE entry=34;
UPDATE trinity_string SET content_default=' [激活]' WHERE entry=35;
UPDATE trinity_string SET content_default=' [完成]' WHERE entry=36;
UPDATE trinity_string SET content_default=' (离线)' WHERE entry=37;
UPDATE trinity_string SET content_default='开' WHERE entry=38;
UPDATE trinity_string SET content_default='关' WHERE entry=39;
UPDATE trinity_string SET content_default='你是: %s' WHERE entry=40;
UPDATE trinity_string SET content_default='显示' WHERE entry=41;
UPDATE trinity_string SET content_default='隐藏' WHERE entry=42;
UPDATE trinity_string SET content_default='完成' WHERE entry=43;
UPDATE trinity_string SET content_default='你' WHERE entry=44;
UPDATE trinity_string SET content_default=' <未知> ' WHERE entry=45;
UPDATE trinity_string SET content_default='<错误>' WHERE entry=46;
UPDATE trinity_string SET content_default='<查无此人>' WHERE entry=47;
UPDATE trinity_string SET content_default='未知' WHERE entry=48;
UPDATE trinity_string SET content_default='你必须达到 %u 级后进入.' WHERE entry=49;
UPDATE trinity_string SET content_default='你必须达到 %u 级,并且拥有道具 %s 方可进入.' WHERE entry=50;
UPDATE trinity_string SET content_default='你好! 准备学习什么技能吗?' WHERE entry=51;
UPDATE trinity_string SET content_default='全区广播:\n' WHERE entry=100;
UPDATE trinity_string SET content_default='%s 已被远距传送.' WHERE entry=102;
UPDATE trinity_string SET content_default='你可以召唤一个玩家到你的副本，前提是必须在同一队伍，而且你是队长.' WHERE entry=103;
UPDATE trinity_string SET content_default='你无法传送到玩家 %s 的副本，因为你们不在同一队伍.' WHERE entry=104;
UPDATE trinity_string SET content_default='传送到不是同一队伍的玩家 %s 的副本需要开启ＧＭ模式.' WHERE entry=105;
UPDATE trinity_string SET content_default='你无法传送到玩家  %s 从副本到副本.' WHERE entry=106;
UPDATE trinity_string SET content_default='你不能召唤这个玩家 %s 从副本到副本.' WHERE entry=107;
UPDATE trinity_string SET content_default='你正在召唤 %s%s.' WHERE entry=108;
UPDATE trinity_string SET content_default='系统提示：你正在被 %s 召唤中.' WHERE entry=109;
UPDATE trinity_string SET content_default='你正在传送  %s%s to %s.' WHERE entry=110;
UPDATE trinity_string SET content_default='系统提示：你正在被 %s 传送.' WHERE entry=111;
UPDATE trinity_string SET content_default='玩家 (%s) 不存在.' WHERE entry=112;
UPDATE trinity_string SET content_default='出现在 %s 的地点.' WHERE entry=113;
UPDATE trinity_string SET content_default='%s 出现在你的位置.' WHERE entry=114;
UPDATE trinity_string SET content_default='无效参数.' WHERE entry=115;
UPDATE trinity_string SET content_default='没有选定角色.' WHERE entry=116;
UPDATE trinity_string SET content_default='%s 不在同一小组里.' WHERE entry=117;
UPDATE trinity_string SET content_default='你改变了 %s 的血量值 HP to %i/%i.' WHERE entry=118;
UPDATE trinity_string SET content_default='%s 改变了你的血量值 HP 到 %i/%i.' WHERE entry=119;
UPDATE trinity_string SET content_default='你改变了 %s 的魔法值 MANA 到 %i/%i.' WHERE entry=120;
UPDATE trinity_string SET content_default='%s 改变了你的魔法值 MANA 到 %i/%i.' WHERE entry=121;
UPDATE trinity_string SET content_default='你改变了 %s 的能量值 ENERGY 到 %i/%i.' WHERE entry=122;
UPDATE trinity_string SET content_default='%s 改变了你的能量值 ENERGY 到 %i/%i.' WHERE entry=123;
UPDATE trinity_string SET content_default='当前的能量: %u' WHERE entry=124;
UPDATE trinity_string SET content_default='你改变了 %s 的怒气值 RAGE 到 %i/%i.' WHERE entry=125;
UPDATE trinity_string SET content_default='%s 改变了你的怒气值 RAGE 到 %i/%i.' WHERE entry=126;
UPDATE trinity_string SET content_default='你改变了 %s 的等级 LVL 到 %i.' WHERE entry=127;
UPDATE trinity_string SET content_default='你设置了所有的速度到 %2.2f 从基础值 %s.' WHERE entry=137;
UPDATE trinity_string SET content_default='%s 设置了你所有的速度到 %2.2f 从基础值.' WHERE entry=138;
UPDATE trinity_string SET content_default='你设置了移动速度到 %2.2f 从基础值 %s.' WHERE entry=139;
UPDATE trinity_string SET content_default='%s 设置了你的移动速度到 %2.2f 从基础值.' WHERE entry=140;
UPDATE trinity_string SET content_default='你设置了游泳速度到 %2.2f 从基础值 %s.' WHERE entry=141;
UPDATE trinity_string SET content_default='%s 设置了你的游泳速度到 %2.2f 从基础值.' WHERE entry=142;
UPDATE trinity_string SET content_default='设置了后退速度到 %2.2f 从基础值 %s.' WHERE entry=143;
UPDATE trinity_string SET content_default='%s 设置了你的后退速度到 %2.2f 从基础值.' WHERE entry=144;
UPDATE trinity_string SET content_default='你设置了飞行速度到 %2.2f 从基础值 %s.' WHERE entry=145;
UPDATE trinity_string SET content_default='%s 设置你的飞行速度到 %2.2f 从基础值.' WHERE entry=146;
UPDATE trinity_string SET content_default='你设置了这个比例 %2.2f of %s.' WHERE entry=147;
UPDATE trinity_string SET content_default='%s 设置你的比例为 %2.2f.' WHERE entry=148;
UPDATE trinity_string SET content_default='没有此类骑术.' WHERE entry=149;
UPDATE trinity_string SET content_default='你把一个骑术送给 %s.' WHERE entry=150;
UPDATE trinity_string SET content_default='%s 送给你一个骑术.' WHERE entry=151;
UPDATE trinity_string SET content_default='你拿走了所有的铜币从 %s.' WHERE entry=153;
UPDATE trinity_string SET content_default='%s 拿走了你所有的铜币.' WHERE entry=154;
UPDATE trinity_string SET content_default='你拿走了 %i 铜币从 %s.' WHERE entry=155;
UPDATE trinity_string SET content_default='%s 拿走了 %i 铜币从你这里.' WHERE entry=156;
UPDATE trinity_string SET content_default='你把 %i 铜币给了 %s.' WHERE entry=157;
UPDATE trinity_string SET content_default='%s 给你 %i  铜币.' WHERE entry=158;
UPDATE trinity_string SET content_default='你听到声音 %u.' WHERE entry=159;
UPDATE trinity_string SET content_default='远距传送地点表是空的!' WHERE entry=163;
UPDATE trinity_string SET content_default='远距传送地点没被发现!' WHERE entry=164;
UPDATE trinity_string SET content_default='需要搜索参数.' WHERE entry=165;
UPDATE trinity_string SET content_default='没有远距传物地点匹配您的请求.' WHERE entry=166;
UPDATE trinity_string SET content_default='发现地点是: ' WHERE entry=168;
UPDATE trinity_string SET content_default='邮件寄给 %s' WHERE entry=169;
UPDATE trinity_string SET content_default='你试着听声音 %u 但是它并不存在.' WHERE entry=170;
UPDATE trinity_string SET content_default='没有选择.' WHERE entry=200;
UPDATE trinity_string SET content_default='这个名字长度超过了 %i 字符.' WHERE entry=202;
UPDATE trinity_string SET content_default='错误,名字只能包含字符 A-Z 和 a-z.' WHERE entry=203;
UPDATE trinity_string SET content_default='次级名字太长超过了 %i 字符.' WHERE entry=204;
UPDATE trinity_string SET content_default='未能实施.' WHERE entry=205;
UPDATE trinity_string SET content_default='物品 ''%i'' ''%s'' 以加入到列表且最大数 ''%i'' 复生时间 ''%i''' WHERE entry=206;
UPDATE trinity_string SET content_default='物品 ''%i'' 在数据库里没有找到.' WHERE entry=207;
UPDATE trinity_string SET content_default='物品 ''%i'' ''%s'' 已经从商人列表中删除.' WHERE entry=208;
UPDATE trinity_string SET content_default='物品 ''%i'' 没有找到在商人的列表里.' WHERE entry=209;
UPDATE trinity_string SET content_default='法术 %s 重置.' WHERE entry=211;
UPDATE trinity_string SET content_default='法术 %s 将在下次登陆时重置.' WHERE entry=212;
UPDATE trinity_string SET content_default='天赋 %s 重置.' WHERE entry=213;
UPDATE trinity_string SET content_default='天赋 %s 将在下次登陆时重置.' WHERE entry=214;
UPDATE trinity_string SET content_default='你的法术已经重置了.' WHERE entry=215;
UPDATE trinity_string SET content_default='你的天赋已经重置了.' WHERE entry=216;
UPDATE trinity_string SET content_default='未知的参数 ''%s'' 为 .resetall 命令. 键入完整的正确参数名字.' WHERE entry=217;
UPDATE trinity_string SET content_default='法术将重置在所有玩家在重新登录后. 强烈推荐重新登录!' WHERE entry=218;
UPDATE trinity_string SET content_default='天赋将重置在所有玩家在重新登录后. 强烈推荐重新登录!' WHERE entry=219;
UPDATE trinity_string SET content_default='生物 (GUID: %u) 没有飞行点发现.' WHERE entry=220;
UPDATE trinity_string SET content_default='生物 (GUID: %u) 飞行终点没有找到.' WHERE entry=221;
UPDATE trinity_string SET content_default='生物 (GUID: %u) 没有飞行点发现 - 请用  ''wpguid''. 现在设法发现它由它的位置...' WHERE entry=222;
UPDATE trinity_string SET content_default='生物 (GUID: %u) 没有飞行点发现 - 这是一个MaNGOS db 问题 (single float).' WHERE entry=223;
UPDATE trinity_string SET content_default='选择的生物被忽略 - 提供的 GUID 已经被占用.' WHERE entry=224;
UPDATE trinity_string SET content_default='生物 (GUID: %u) 没有找到.' WHERE entry=225;
UPDATE trinity_string SET content_default='您必须选择一个视觉飞行点.' WHERE entry=226;
UPDATE trinity_string SET content_default='没有找到视觉飞行点.' WHERE entry=227;
UPDATE trinity_string SET content_default='不能创建视觉飞行点的 生物ID: %d' WHERE entry=228;
UPDATE trinity_string SET content_default='所有视觉飞行点消除.' WHERE entry=229;
UPDATE trinity_string SET content_default='不能创建 飞行点-生物的 ID: %d' WHERE entry=230;
UPDATE trinity_string SET content_default='没有 GUID 被提供.' WHERE entry=231;
UPDATE trinity_string SET content_default='没有提供飞行点数值.' WHERE entry=232;
UPDATE trinity_string SET content_default='根据要求为 ''%s''.' WHERE entry=233;
UPDATE trinity_string SET content_default='飞行点 %i 添加到 GUID: %d' WHERE entry=234;
UPDATE trinity_string SET content_default='飞行点 %d 已添加.' WHERE entry=235;
UPDATE trinity_string SET content_default='飞行点已变动.' WHERE entry=236;
UPDATE trinity_string SET content_default='飞行点 %s 已修改.' WHERE entry=237;
UPDATE trinity_string SET content_default='飞行点出口成功.' WHERE entry=238;
UPDATE trinity_string SET content_default='没有飞行点被发现在数据库里.' WHERE entry=239;
UPDATE trinity_string SET content_default='文件已导入.' WHERE entry=240;
UPDATE trinity_string SET content_default='飞行点取消.' WHERE entry=241;
UPDATE trinity_string SET content_default='警告: 不能删除这个飞行点从世界里且 ID: %d' WHERE entry=242;
UPDATE trinity_string SET content_default='出现这种情况，是因为飞行点过于远离你.' WHERE entry=243;
UPDATE trinity_string SET content_default='这个飞行点已经从数据库删除, 但不是从世界这里.' WHERE entry=244;
UPDATE trinity_string SET content_default='他们将消失，当服务器重新启动之后.' WHERE entry=245;
UPDATE trinity_string SET content_default='飞行点 %d: 生物信息: %s, GUID: %d' WHERE entry=246;
UPDATE trinity_string SET content_default='等待时间: %d' WHERE entry=247;
UPDATE trinity_string SET content_default='模型 %d: %d' WHERE entry=248;
UPDATE trinity_string SET content_default='表情: %d' WHERE entry=249;
UPDATE trinity_string SET content_default='技能: %d' WHERE entry=250;
UPDATE trinity_string SET content_default='文本%d (ID: %i): %s' WHERE entry=251;
UPDATE trinity_string SET content_default='AI脚本: %s' WHERE entry=252;
UPDATE trinity_string SET content_default='强制修改玩家名 %s, 将于下次登录时生效.' WHERE entry=253;
UPDATE trinity_string SET content_default='强制修改玩家名 %s (GUID #%u), 将于下次登录时生效.' WHERE entry=254;
UPDATE trinity_string SET content_default='飞行点-生物 (GUID: %u) 没有找到.' WHERE entry=255;
UPDATE trinity_string SET content_default='不能查找NPC...' WHERE entry=256;
UPDATE trinity_string SET content_default='生物运动方式设置为 ''%s'', 飞行点去除 (如果任何).' WHERE entry=257;
UPDATE trinity_string SET content_default='生物运动方式设置为 ''%s'', 飞行点没有去除.' WHERE entry=258;
UPDATE trinity_string SET content_default='错误值, 请用 on 或 off ' WHERE entry=259;
UPDATE trinity_string SET content_default='设置已保存.' WHERE entry=260;
UPDATE trinity_string SET content_default='设置已保存, 你可能需要重新清理你的客户缓存.' WHERE entry=261;
UPDATE trinity_string SET content_default='区域触发(传送门) ID %u 没有发现! ' WHERE entry=262;
UPDATE trinity_string SET content_default='目标地图或坐标无效 (X: %f Y: %f MapId: %u)' WHERE entry=263;
UPDATE trinity_string SET content_default='区域传送门无效 (X: %f Y: %f AreaId: %u)' WHERE entry=264;
UPDATE trinity_string SET content_default='没任何发现!' WHERE entry=266;
UPDATE trinity_string SET content_default='对象没有找到!' WHERE entry=267;
UPDATE trinity_string SET content_default='生物没有找到!' WHERE entry=268;
UPDATE trinity_string SET content_default='警告: 怪物发现超过一次 - 你将使用的是第一个在DB数据里的记录.' WHERE entry=269;
UPDATE trinity_string SET content_default='生物已经移除.' WHERE entry=270;
UPDATE trinity_string SET content_default='生物已经移动. ' WHERE entry=271;
UPDATE trinity_string SET content_default='生物 (GUID:%u) 必须与玩家在同样的地图!' WHERE entry=272;
UPDATE trinity_string SET content_default='游戏对象 (GUID: %u) 没有找到.' WHERE entry=273;
UPDATE trinity_string SET content_default='游戏对象 (GUID: %u) 有一个参考于没有找到生物 %u 是名单, 不能被删除.' WHERE entry=274;
UPDATE trinity_string SET content_default='游戏对象 (GUID: %u) 去除.' WHERE entry=275;
UPDATE trinity_string SET content_default='游戏对象 (GUID: %u) 转动.' WHERE entry=276;
UPDATE trinity_string SET content_default='游戏对象 (GUID: %u) 移动.' WHERE entry=277;
UPDATE trinity_string SET content_default='你必须选择一个商人' WHERE entry=278;
UPDATE trinity_string SET content_default='你必须使用物品的id' WHERE entry=279;
UPDATE trinity_string SET content_default='商人设置了太多的物品 (最多128)' WHERE entry=280;
UPDATE trinity_string SET content_default='你不能踢出你自己，使用退出代替.' WHERE entry=281;
UPDATE trinity_string SET content_default='角色 %s 已踢出.' WHERE entry=282;
UPDATE trinity_string SET content_default='接受悄悄话: %s' WHERE entry=284;
UPDATE trinity_string SET content_default='接受悄悄话: ON' WHERE entry=285;
UPDATE trinity_string SET content_default='接受悄悄话: OFF' WHERE entry=286;
UPDATE trinity_string SET content_default='生物 (GUID: %u) 没有找到.' WHERE entry=287;
UPDATE trinity_string SET content_default='票数量: %i 出示新的票: %s ' WHERE entry=288;
UPDATE trinity_string SET content_default='新票开始于 %s' WHERE entry=289;
UPDATE trinity_string SET content_default='新票显示: ON' WHERE entry=291;
UPDATE trinity_string SET content_default='新票显示: OFF' WHERE entry=292;
UPDATE trinity_string SET content_default='票 %i 不存在.' WHERE entry=293;
UPDATE trinity_string SET content_default='所有票已删除.' WHERE entry=294;
UPDATE trinity_string SET content_default='角色 %s 票已删除.' WHERE entry=295;
UPDATE trinity_string SET content_default='票已删除.' WHERE entry=296;
UPDATE trinity_string SET content_default='复生间隔改变为: %i' WHERE entry=297;
UPDATE trinity_string SET content_default='复生时间改变为: %i' WHERE entry=298;
UPDATE trinity_string SET content_default=' %s 的荣誉被设置到 %u!' WHERE entry=299;
UPDATE trinity_string SET content_default='你的闲谈将被关闭 %u 分钟.' WHERE entry=300;
UPDATE trinity_string SET content_default='你被关闭了 %s 的聊天时间 %u 分钟.' WHERE entry=301;
UPDATE trinity_string SET content_default='玩的聊天已经可以使用.' WHERE entry=302;
UPDATE trinity_string SET content_default='你的聊天已经可以使用.' WHERE entry=303;
UPDATE trinity_string SET content_default='你已经可以使用 %s 的聊天了.' WHERE entry=304;
UPDATE trinity_string SET content_default='没有阵营被发现' WHERE entry=307;
UPDATE trinity_string SET content_default='阵营 %i 未知!' WHERE entry=308;
UPDATE trinity_string SET content_default='无效的参数 %s' WHERE entry=309;
UPDATE trinity_string SET content_default=' [显示状态]' WHERE entry=312;
UPDATE trinity_string SET content_default=' [交战状态]' WHERE entry=313;
UPDATE trinity_string SET content_default=' [和平状态]' WHERE entry=314;
UPDATE trinity_string SET content_default=' [潜行状态]' WHERE entry=315;
UPDATE trinity_string SET content_default='仇恨' WHERE entry=318;
UPDATE trinity_string SET content_default='敌对' WHERE entry=319;
UPDATE trinity_string SET content_default='不友好' WHERE entry=320;
UPDATE trinity_string SET content_default='中立' WHERE entry=321;
UPDATE trinity_string SET content_default='友好的' WHERE entry=322;
UPDATE trinity_string SET content_default='荣誉的' WHERE entry=323;
UPDATE trinity_string SET content_default='尊敬的' WHERE entry=324;
UPDATE trinity_string SET content_default='高贵的' WHERE entry=325;
UPDATE trinity_string SET content_default='真没找到玩家!' WHERE entry=330;
UPDATE trinity_string SET content_default='GM 模式开启' WHERE entry=332;
UPDATE trinity_string SET content_default='GM 模式关闭' WHERE entry=333;
UPDATE trinity_string SET content_default='|cffff0000[系统信息]:|rScripts reloaded' WHERE entry=400;
UPDATE trinity_string SET content_default='你改变了 %s 的安全等级为 %i.' WHERE entry=401;
UPDATE trinity_string SET content_default='%s 改变了你的安全等级为 %i.' WHERE entry=402;
UPDATE trinity_string SET content_default='你这是低的防护等级.' WHERE entry=403;
UPDATE trinity_string SET content_default='生物移动点取消.' WHERE entry=404;
UPDATE trinity_string SET content_default='生物移动点生效.' WHERE entry=405;
UPDATE trinity_string SET content_default='这个区域的天气不能被更改.' WHERE entry=406;
UPDATE trinity_string SET content_default='本服务器天气系统取消.' WHERE entry=407;
UPDATE trinity_string SET content_default='%s 被禁止的为 %s. 操作: %s.' WHERE entry=408;
UPDATE trinity_string SET content_default='%s 被永久禁止的为 %s.' WHERE entry=409;
UPDATE trinity_string SET content_default='%s %s 没有发现.' WHERE entry=410;
UPDATE trinity_string SET content_default='%s 已解除禁止.' WHERE entry=411;
UPDATE trinity_string SET content_default='出现错误取消禁令 %s.' WHERE entry=412;
UPDATE trinity_string SET content_default='没有这个帐户.' WHERE entry=413;
UPDATE trinity_string SET content_default='没有这个角色.' WHERE entry=414;
UPDATE trinity_string SET content_default='没有这样的IP 在禁止名单.' WHERE entry=415;
UPDATE trinity_string SET content_default='账号 %s 从来没被禁止.' WHERE entry=416;
UPDATE trinity_string SET content_default='历史禁止帐户 %s:' WHERE entry=417;
UPDATE trinity_string SET content_default='禁止日期: %s 禁止时间: %s 激活间隔: %s  原因: %s 操作者: %s' WHERE entry=418;
UPDATE trinity_string SET content_default='Inf.' WHERE entry=419;
UPDATE trinity_string SET content_default='从未' WHERE entry=420;
UPDATE trinity_string SET content_default='是' WHERE entry=421;
UPDATE trinity_string SET content_default='不' WHERE entry=422;
UPDATE trinity_string SET content_default='IP地址: %s 禁止日期: %s 解除禁止日期: %s 剩余: %s R' WHERE entry=423;
UPDATE trinity_string SET content_default='没有匹配的IP禁止地址.' WHERE entry=424;
UPDATE trinity_string SET content_default='没有匹配的帐户.' WHERE entry=425;
UPDATE trinity_string SET content_default='没有禁用的账号相匹配.' WHERE entry=426;
UPDATE trinity_string SET content_default='下面的IP地址符合您的格局:' WHERE entry=427;
UPDATE trinity_string SET content_default='以下帐户匹配您的查询:' WHERE entry=428;
UPDATE trinity_string SET content_default='你学会了许多法术或技能.' WHERE entry=429;
UPDATE trinity_string SET content_default='你已经学会了所有的会职业法术.' WHERE entry=430;
UPDATE trinity_string SET content_default='你已经学会了所有的本职业天赋.' WHERE entry=431;
UPDATE trinity_string SET content_default='你已经学会了所有的语言.' WHERE entry=432;
UPDATE trinity_string SET content_default='你学会了所有手工艺技能和食谱.' WHERE entry=433;
UPDATE trinity_string SET content_default='不能查找 ''%s''' WHERE entry=434;
UPDATE trinity_string SET content_default='无效的物品 id: %u' WHERE entry=435;
UPDATE trinity_string SET content_default='没有找到物品!' WHERE entry=436;
UPDATE trinity_string SET content_default='无效的游戏物品对象 id: %u' WHERE entry=437;
UPDATE trinity_string SET content_default='找到物品 %u: %u ( 库存 %u 邮件 %u 拍卖 %u )' WHERE entry=438;
UPDATE trinity_string SET content_default='找到物品对象 %u: %u' WHERE entry=439;
UPDATE trinity_string SET content_default='无效的生物 id: %u' WHERE entry=440;
UPDATE trinity_string SET content_default='找到生物 %u: %u' WHERE entry=441;
UPDATE trinity_string SET content_default='没有地区被发现!' WHERE entry=442;
UPDATE trinity_string SET content_default='没有找到物品集!' WHERE entry=443;
UPDATE trinity_string SET content_default='没有找到此技能!' WHERE entry=444;
UPDATE trinity_string SET content_default='没有找到此法术!' WHERE entry=445;
UPDATE trinity_string SET content_default='没有找到此任务!' WHERE entry=446;
UPDATE trinity_string SET content_default='没有找到此生物!' WHERE entry=447;
UPDATE trinity_string SET content_default='没有找到此游戏物品对象!' WHERE entry=448;
UPDATE trinity_string SET content_default='墓地 #%u 不存在.' WHERE entry=449;
UPDATE trinity_string SET content_default='墓地 #%u 已经连接到区域 #%u (当前).' WHERE entry=450;
UPDATE trinity_string SET content_default='墓地 #%u 连接到区域 #%u (当前).' WHERE entry=451;
UPDATE trinity_string SET content_default='墓地 #%u 不能连接到子区域或不存在的区域 #%u (内部错误).' WHERE entry=452;
UPDATE trinity_string SET content_default='没有阵营在墓地且 id= #%u , 请修复你的DB数据库' WHERE entry=454;
UPDATE trinity_string SET content_default='错误的队伍, 请修复你的数据库' WHERE entry=455;
UPDATE trinity_string SET content_default='任何' WHERE entry=456;
UPDATE trinity_string SET content_default='联盟' WHERE entry=457;
UPDATE trinity_string SET content_default='部落' WHERE entry=458;
UPDATE trinity_string SET content_default='墓地ID #%u (阵营faction: %s) 是最近的距此区域zoneID #%u.' WHERE entry=459;
UPDATE trinity_string SET content_default='区域Zone #%u 没有一个连接的墓地.' WHERE entry=460;
UPDATE trinity_string SET content_default='区域Zone #%u 没有一个连接的墓地为阵营faction: %s.' WHERE entry=461;
UPDATE trinity_string SET content_default='远距传物地点已经存在!' WHERE entry=462;
UPDATE trinity_string SET content_default='远距传送地点增加.' WHERE entry=463;
UPDATE trinity_string SET content_default='远距传送地点没增加: 数据库错误.' WHERE entry=464;
UPDATE trinity_string SET content_default='远距传送地点被删除.' WHERE entry=465;
UPDATE trinity_string SET content_default='目标单位(unit)有 %d 光环auras:' WHERE entry=467;
UPDATE trinity_string SET content_default='任务 %u 没有找到.' WHERE entry=471;
UPDATE trinity_string SET content_default='任务 %u 由物品触发. 为正确工作, 请, 添加物品到库里并且开始这个任务的正常方式: .additem %u' WHERE entry=472;
UPDATE trinity_string SET content_default='任务清除.' WHERE entry=473;
UPDATE trinity_string SET content_default=' [奖赏]' WHERE entry=474;
UPDATE trinity_string SET content_default=' [完成]' WHERE entry=475;
UPDATE trinity_string SET content_default='%s 的飞行模式为 %s' WHERE entry=477;
UPDATE trinity_string SET content_default='操作代码Opcode %u 发送到(sent to) %s' WHERE entry=478;
UPDATE trinity_string SET content_default='角色加载成功!' WHERE entry=479;
UPDATE trinity_string SET content_default='加载角色失败!' WHERE entry=480;
UPDATE trinity_string SET content_default='卸载角色成功!' WHERE entry=481;
UPDATE trinity_string SET content_default='卸载角色失败!' WHERE entry=482;
UPDATE trinity_string SET content_default='魔法 %u 破裂，并且不允许使用或学习!' WHERE entry=483;
UPDATE trinity_string SET content_default='技能值 %u (%s) 为角色 %s 设置到 %u 并且当前最大设置到 %u (没有固定(天赋)奖励).' WHERE entry=484;
UPDATE trinity_string SET content_default='角色 %s 必须拥有技能 %u (%s) 在使用这个命令之前.' WHERE entry=485;
UPDATE trinity_string SET content_default='错误的技能 id (%u)' WHERE entry=486;
UPDATE trinity_string SET content_default='你学会了ＧＭ默认的法术和技能.' WHERE entry=487;
UPDATE trinity_string SET content_default='你已经学了这个法术.' WHERE entry=488;
UPDATE trinity_string SET content_default='目标Target(%s) 已经学习了那些法术.' WHERE entry=489;
UPDATE trinity_string SET content_default='%s 不懂那些法术.' WHERE entry=490;
UPDATE trinity_string SET content_default='您已经忘记了那个法术.' WHERE entry=491;
UPDATE trinity_string SET content_default='所有的法术冷却清除 for %s.' WHERE entry=492;
UPDATE trinity_string SET content_default='法术 %u 冷却清除 for %s.' WHERE entry=493;
UPDATE trinity_string SET content_default='命令: Additem, itemId = %i, amount = %i' WHERE entry=494;
UPDATE trinity_string SET content_default='命令: Additemset, itemsetId = %i' WHERE entry=495;
UPDATE trinity_string SET content_default='移除物品ID = %i, amount = %i from %s' WHERE entry=496;
UPDATE trinity_string SET content_default='不能创建物品  ''%i'' (数量amount: %i)' WHERE entry=497;
UPDATE trinity_string SET content_default='系统提示：你需要提供一个公会名字!' WHERE entry=498;
UPDATE trinity_string SET content_default='系统提示：玩家没有被找到!' WHERE entry=499;
UPDATE trinity_string SET content_default='系统提示：玩家已经有一个公会!' WHERE entry=500;
UPDATE trinity_string SET content_default='公会没被创建! (是否已经存在?)' WHERE entry=501;
UPDATE trinity_string SET content_default='没有物品从物品库 ''%u'' 里找到.' WHERE entry=502;
UPDATE trinity_string SET content_default='物品 ''%i'' ''%s''  背包 %i' WHERE entry=504;
UPDATE trinity_string SET content_default='物品 ''%i'' 不存在.' WHERE entry=505;
UPDATE trinity_string SET content_default='物品 ''%i'' ''%s'' 已加入背包 %i' WHERE entry=506;
UPDATE trinity_string SET content_default='物品保存失败!' WHERE entry=507;
UPDATE trinity_string SET content_default='副本ID: %u' WHERE entry=547;
UPDATE trinity_string SET content_default='玩家%s %s (guid: %u) 帐号: %s (id: %u) G M等级: %u 最后IP: %s 最后登陆: %s Latency: %ums' WHERE entry=548;
UPDATE trinity_string SET content_default='已登录时间: %s 等级: %u 金钱: %ug%us%uc' WHERE entry=549;
UPDATE trinity_string SET content_default='%s 探索了所有地区.' WHERE entry=551;
UPDATE trinity_string SET content_default='%s 没有更多的探索区.' WHERE entry=552;
UPDATE trinity_string SET content_default='%s 你探索了所有地带.' WHERE entry=553;
UPDATE trinity_string SET content_default='%s 你掩藏了所有区域.' WHERE entry=554;
UPDATE trinity_string SET content_default='悬停启用' WHERE entry=555;
UPDATE trinity_string SET content_default='你现在处于隐身状态.' WHERE entry=577;
UPDATE trinity_string SET content_default='你现在处于可见状态.' WHERE entry=578;
UPDATE trinity_string SET content_default='玩家 %s 学会了所有的本种族本职业的魔法,包括任何奖励的技能.' WHERE entry=580;
UPDATE trinity_string SET content_default='没有事件被找到!' WHERE entry=584;
UPDATE trinity_string SET content_default='事件不存在!' WHERE entry=585;
UPDATE trinity_string SET content_default='事件 %u 已经开始!' WHERE entry=587;
UPDATE trinity_string SET content_default='事件 %u 没有开始!' WHERE entry=588;
UPDATE trinity_string SET content_default='联盟获得胜利!' WHERE entry=600;
UPDATE trinity_string SET content_default='部落获得胜利!' WHERE entry=601;
UPDATE trinity_string SET content_default='战场战歌峡谷争夺1分钟倒计时中...' WHERE entry=602;
UPDATE trinity_string SET content_default='战场战歌峡谷争夺，在30秒后开始。大家做好准备!' WHERE entry=603;
UPDATE trinity_string SET content_default='战场战歌峡谷争夺正式开始!' WHERE entry=604;
UPDATE trinity_string SET content_default='$n 夺取了部落旗子!' WHERE entry=605;
UPDATE trinity_string SET content_default='$n 夺取了联盟旗子!' WHERE entry=606;
UPDATE trinity_string SET content_default='部落旗子被 $n 降下!' WHERE entry=607;
UPDATE trinity_string SET content_default='联盟旗子被 $n 降下!' WHERE entry=608;
UPDATE trinity_string SET content_default='联盟旗子被 $n 返回了到它的基地!' WHERE entry=609;
UPDATE trinity_string SET content_default='部落旗子被 $n 返回了到它的基地!' WHERE entry=610;
UPDATE trinity_string SET content_default='部落旗子被 $n 拾起!' WHERE entry=611;
UPDATE trinity_string SET content_default='魔兽世界：联盟旗子被 $n 拾起!' WHERE entry=612;
UPDATE trinity_string SET content_default='旗子现在被安置在他们的基地.' WHERE entry=613;
UPDATE trinity_string SET content_default='联盟旗帜已经被重置' WHERE entry=614;
UPDATE trinity_string SET content_default='联盟旗帜已经被重置!' WHERE entry=615;
UPDATE trinity_string SET content_default='战场暴风之眼争夺1分钟倒计时中....' WHERE entry=636;
UPDATE trinity_string SET content_default='战场暴风之眼争夺，在30秒后开始。大家做好准备!.' WHERE entry=637;
UPDATE trinity_string SET content_default='战场暴风之眼争夺正式开始!!' WHERE entry=638;
UPDATE trinity_string SET content_default='联盟' WHERE entry=650;
UPDATE trinity_string SET content_default='部落' WHERE entry=651;
UPDATE trinity_string SET content_default='此 %s 采取了 %s' WHERE entry=657;
UPDATE trinity_string SET content_default='$n 保卫了  %s' WHERE entry=658;
UPDATE trinity_string SET content_default='$n 攻击了  %s' WHERE entry=659;
UPDATE trinity_string SET content_default='$n 主持这个 %s 吧! 如果听之任之, 这个 %s 将在1 分钟之内控制它!' WHERE entry=660;
UPDATE trinity_string SET content_default='战场阿拉西盆地争夺1分钟倒计时中...' WHERE entry=661;
UPDATE trinity_string SET content_default='战场阿拉西盆地争夺，在30秒后开始。大家做好准备!' WHERE entry=662;
UPDATE trinity_string SET content_default='战场阿拉西盆地争夺正式开始!' WHERE entry=663;
UPDATE trinity_string SET content_default='联盟已收集到$1776W资源, 并已接近胜利!' WHERE entry=664;
UPDATE trinity_string SET content_default='部落已收集到$1777W资源, 并已接近胜利!' WHERE entry=665;
UPDATE trinity_string SET content_default='你在最近的 %s 战斗之后,我们努力想为你颁发一个荣誉标志却没有成功,结束后你会发现这个荣誉标志的,但不是此刻,感谢你在 %s 的战斗.' WHERE entry=666;
UPDATE trinity_string SET content_default='旗子已经被降下!' WHERE entry=686;
UPDATE trinity_string SET content_default='旗帜已经被重置' WHERE entry=687;
UPDATE trinity_string SET content_default='你必须达到等级  %u 才能进入竞技场.' WHERE entry=700;
UPDATE trinity_string SET content_default='一分钟后竞技场争斗开始!' WHERE entry=701;
UPDATE trinity_string SET content_default='三十秒后竞技场争斗开始!' WHERE entry=702;
UPDATE trinity_string SET content_default='十五秒后竞技场争斗开始!' WHERE entry=703;
UPDATE trinity_string SET content_default='竞技场争斗开始了!' WHERE entry=704;
UPDATE trinity_string SET content_default='你必须等待 %s 才能继续喊话.' WHERE entry=705;
UPDATE trinity_string SET content_default='这些道具在装备/存放中出现一个问题.' WHERE entry=706;
UPDATE trinity_string SET content_default='%s 免打扰状态下无法收到悄悄话: %s' WHERE entry=707;
UPDATE trinity_string SET content_default='%s 不在机器旁: %s' WHERE entry=708;
UPDATE trinity_string SET content_default='请勿打扰' WHERE entry=709;
UPDATE trinity_string SET content_default='不在机器旁' WHERE entry=710;
UPDATE trinity_string SET content_default='|cffff0000[战场公告]:|r %s -- [%u-%u] 联盟: 目前%u人 (需: %u人), 部落: 目前%u人 (需: %u人)|r' WHERE entry=712;
UPDATE trinity_string SET content_default='你的等级必须达到 %u 才能加入一个竞技场队伍!' WHERE entry=713;
UPDATE trinity_string SET content_default='不能达到进入战场的要求.' WHERE entry=715;
UPDATE trinity_string SET content_default='单人战场开启.战场设置（1V0）.' WHERE entry=739;
UPDATE trinity_string SET content_default='战场模式已更改为：正常状态.' WHERE entry=740;
UPDATE trinity_string SET content_default='公会管理员' WHERE entry=811;
UPDATE trinity_string SET content_default='官员' WHERE entry=812;
UPDATE trinity_string SET content_default='精英' WHERE entry=813;
UPDATE trinity_string SET content_default='会员' WHERE entry=814;
UPDATE trinity_string SET content_default='新人' WHERE entry=815;
UPDATE trinity_string SET content_default='没有找到宠物。' WHERE entry=1123;
UPDATE trinity_string SET content_default='错误的宠物类型。' WHERE entry=1124;
UPDATE trinity_string SET content_default='联盟' WHERE entry=1300;
UPDATE trinity_string SET content_default='部落' WHERE entry=1301;
UPDATE trinity_string SET content_default='你必须在一个团队中才能进入此副本.' WHERE entry=5007;
UPDATE trinity_string SET content_default='开始在服务器播放音乐: %u ' WHERE entry=5009;
UPDATE trinity_string SET content_default='没有找到地图!' WHERE entry=5012;
UPDATE trinity_string SET content_default='[竞技场]' WHERE entry=5016;
UPDATE trinity_string SET content_default='[副本重置时间: %s]' WHERE entry=5017;
UPDATE trinity_string SET content_default='[地下城重置时间: %s]' WHERE entry=5018;
UPDATE trinity_string SET content_default='泰坦大门已经被联盟占领!' WHERE entry=10063;
UPDATE trinity_string SET content_default='泰坦大门已经被部落占领!' WHERE entry=10064;
UPDATE trinity_string SET content_default='%s 已经被破坏了!' WHERE entry=10061;
UPDATE trinity_string SET content_default='第一回合-  完成!' WHERE entry=10062;
UPDATE trinity_string SET content_default='远古海滩战斗开启!勇士们.为了我们的荣耀，冲！' WHERE entry=10059;
UPDATE trinity_string SET content_default='%s 受到攻击!' WHERE entry=10060;
UPDATE trinity_string SET content_default='远古海滩战场将在30秒内开启!请各位玩家准备好.' WHERE entry=10058;
UPDATE trinity_string SET content_default='远古海滩战场将在2分钟内开启!' WHERE entry=10056;
UPDATE trinity_string SET content_default='远古海滩战场将在1分钟内开启!' WHERE entry=10057;
UPDATE trinity_string SET content_default='这个是关闭着的.' WHERE entry=5008;
UPDATE trinity_string SET content_default='编码: %u' WHERE entry=5024;
UPDATE trinity_string SET content_default='类型: %u' WHERE entry=5025;
UPDATE trinity_string SET content_default='外观编码: %u' WHERE entry=5026;
UPDATE trinity_string SET content_default='名称: %s' WHERE entry=5027;
UPDATE trinity_string SET content_default='物品 ''%i'' 已经在商人的列表里存在了.' WHERE entry=210;
UPDATE trinity_string SET content_default='城市' WHERE entry=819;
UPDATE trinity_string SET content_default='无效的目标' WHERE entry=63;
UPDATE trinity_string SET content_default='你必须达到58级，才能使用这个功能.' WHERE entry=65;
UPDATE trinity_string SET content_default='本次战斗将在2分钟内开始.' WHERE entry=1205;
UPDATE trinity_string SET content_default='本次战斗将在1分钟内开始.' WHERE entry=1206;
UPDATE trinity_string SET content_default='战斗开始了！' WHERE entry=1208;
UPDATE trinity_string SET content_default='本次战斗将在30秒内开始!' WHERE entry=1207;
UPDATE trinity_string SET content_default='已被联盟占领' WHERE entry=1209;
UPDATE trinity_string SET content_default='已被部落占领' WHERE entry=1210;
UPDATE trinity_string SET content_default='%s 赢得了胜利!' WHERE entry=1211;
UPDATE trinity_string SET content_default='西大门 %s 被破坏!' WHERE entry=1212;
UPDATE trinity_string SET content_default='车间' WHERE entry=1220;
UPDATE trinity_string SET content_default='码头' WHERE entry=1221;
UPDATE trinity_string SET content_default='精炼厂' WHERE entry=1222;
UPDATE trinity_string SET content_default='矿厂' WHERE entry=1223;
UPDATE trinity_string SET content_default='机场' WHERE entry=1224;
UPDATE trinity_string SET content_default='命令提示：命令 .pinfo 不支持  ''rep'' 选择,玩家不在线.' WHERE entry=550;
